### ISSUE TITLE
site.js navi.json

### ISSUE THREAD

**Issue by Tim-Raphael** [louis-mudrack/simple-framework#8]
Why is there a navi.json, and why does the navigation markup get generated in the frontend? I think it would be more efficient to just provide the markup using php.

**Comment by louis-mudrack** [comment]
Thats the solution i came up with do build a relativly dynamic navigation where everything works kind of automatic. navi.json is because i am converting the content of the site.contents.php to json and then fetching the data of it via js. Not that familiar with php thats why i used js

**Comment by louis-mudrack** [comment]
--closed
